name: Run Linear Regression Model

on:
  workflow_dispatch:
    inputs:
      x_values:
        description: "Comma-separated numbers"
        required: true
        default: "1.0,2.0,3.0"

jobs:
  run-model:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip numpy

    - name: Prepare input file
      run: |
        echo '{"x": ['$(echo "${{ github.event.inputs.x_values }}" | tr ',' ' ')']}' > input.json

    - name: Run model
      run: python model.py

    - name: Upload predictions
      uses: actions/upload-artifact@v4
      with:
        name: predictions
        path: output.json
